# Sentry 配置项，对应 SentryProperties 配置类
sentry:
  dsn: http://067bdbe9ac244aac8c189b80140fcb5b:33ea373c94c24199a436c7406e784ebc@sentry.qufenqi.com/381  # DSN
  timeout: 60000 # HTTP 请求建立连接超时时间

server:
  port: 18080
